// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbflozvmytrtsgfzivgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZmxvenZteXRydHNnZnppdmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTY0MDIsImV4cCI6MjA2NTkzMjQwMn0.0pky1pptDyQjJDgQWvoMRAML4fk0OwCgW7qhzY1beB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);